### ISSUE TITLE
Why the plugin requires zip, jarsigner and zipalign?

### ISSUE THREAD

**Issue by jtome** [testfairy/testfairy-jenkins-plugin#6]
We are trying to use this plugin in our Continuous Integration environment (Jenkins powered) instead of upload the APK/IPA to TestFairy using *curl* as the last step in our build process, but we are founding a lot of problems.

Our environment has one master Jenkins server (that it does not run any job) and a farm of slaves (linux and OS X servers) that are the responsible for running the build jobs. In each of this slaves the location of the *zip*, *jarsigner* and *zipalign* tools are different. Also for different jobs we have to use different versions of the Android Build Tools (and also of the *zipalign* tool) and we are not able to configure this plugin for this environment.

Why this plugin need this tools?. The build process already produces an APK file that it is already signed and zipaligned, in fact this is the APK that we are uploading to TestFairy using curl (that it is having some problems because of the SSL transport).

**Comment by giltsl** [comment]
Hi,
The plugin can run on slave servers,
To solve the various tools locations, you can add them to the PATH (or copy theme into `/bin/` folder on each slave)

When you are uploading an APK to TestFairy, our system should integrate the TestFairy SDK into it. And after we do it, we need to sign your APK again. 
We are doing it on your Jenkins server so you don’t need to give us your private certifications (Keystore, storepass...).
If you are uploading an IPA, you don’t need to specify any of the tools.

Hope it helps,
TestFairy team.

**Comment by jtome** [comment]
Thanks a lot for the answer but the problem is that each slave can have a different configuration, indeed a different set of tools (different for Linux and OS X slaves). And also we have different jobs in the same slave using different versions of Android Build Tools (this affects to the zipalign tool).

We need to be able to move this configuration to the nodes configuration and/or indeed to the jobs' level. But been able to define this only at global Jenkins environment level it is very restrictive.

**Comment by giltsl** [comment]
You right, your setup is a problem for the current plugin version.
We will look for a suitable solution on the next version.

But for now, I have a temporary solution (not very beautiful, but it should work)
###### In the global Jenkins configuration (TestFairy Android Environment)
* set `"zip full path"` as `/tmp/zip`
* set `"jarsigner full path"` as `/tmp/jarsigner`
* set `"zipalign full path"` as `/tmp/zipalign`

###### In every job add a Execute shell
`cp /THE_RIGHT_LOCATION/zip /tmp/zip`
`cp /THE_RIGHT_LOCATION/jarsigner /tmp/jarsigner`
`cp /THE_RIGHT_LOCATION/zipalign /tmp/zipalign`

Let me know if it worked for you.

**Comment by abakashaGit** [comment]
hi giltsl .
I have an doubt ,I am not getting which path I should give for zip full path.

**Comment by giltsl** [comment]
@abakashaGit 
If you running mac or linux, 
The path will be like "/usr/bin/zip".
If you work on windows,
You should install zip using cygwin (https://cygwin.com/install.html)

**Comment by abakashaGit** [comment]
thanks @giltsl 
I installed 7-Zip and given the "7z" path and it worked.

**Comment by qiyuanchen** [comment]
Hi, I'm facing with the exact same issue.
Has there been any updates on the latest version to handle this gracefully?

**Comment by yairba** [comment]
The latest version solves the problem. Can you please update to the latest?

**Comment by qiyuanchen** [comment]
Hey @yairba we are currently on the latest version. Could you let me know where and how I can access this feature? Thank you

**Comment by yairba** [comment]
Can you please email us to support, so I can get the right teammate to join this chat? thanks!
