### ISSUE TITLE
testfairy android uploader v2.7 failing on Loading changeLog from source control

### ISSUE THREAD

**Issue by astevko** [testfairy/testfairy-jenkins-plugin#9]
I'm updating our jenkins build machine from 6 months of neglect to current release levels.
The latest testfairy jenkins plugin is blocked on "Loading changeLog from source control"
This is immediately after "Error while reading changeLog, Message: <snip>/builds/121/testfairy_change_log (No such file or directory).

This is on a MacBook Air running Jenking v1.621 and using CVS for source control.

Is there a parameter that can prevent this changeLog from interrupting the upload process?

**Comment by giltsl** [comment]
Hi astevko,

The debug line you see on yours Jenkins console is not the reason the upload is stacked.
I need more information, to understand what wrong whit yours upload process.

Can you please send as the rest of the logs.
You can send it to support@testfairy.com
